### ISSUE TITLE
It is not clear how this is different from Snippet Essentials

### ISSUE THREAD

**Issue by 10Dev** [JosefPihrt/Snippetica#1]
It is not clear how this is different from Snippet Essentials

Is it a replacement?

Might be worth updated your docs

**Comment by yannduran** [comment]
In a Q&A question Josef mentions that this is the successor of Snippet Essentials

**Comment by JosefPihrt** [comment]
* Snippetica is virtually the next version of Snippet Essentials.
* Snippetica supports more languages and it has better documentation.
* Snippetica is available for Visual Studio 2017.
