### ISSUE TITLE
Not working Visual Studio 2017

### ISSUE THREAD

**Issue by YQuaresma** [JosefPihrt/Snippetica#3]
Hi, 
Something is wrong. None of the snippet shortcuts are available when I type in the editor. What am I doing wrong?
Snippetica is  a great idea and I would love to be able to use it.

BTW the reference page (http://pihrt.net/Snippetica/Snippets) is also broken. I suggest you have a look on it too.

**Comment by JosefPihrt** [comment]
* Is the extension really installed and enabled? Please check the list of installed extensions.

* Check Code Snippet Manager:
  * Go to - Main Menu - Tools - Code Snippet Manager
  * Select CSharp language.
  * Do you have folder Snippetica.CSharp in your list?

![codesnippetmanager](https://user-images.githubusercontent.com/11931318/29669904-447eaacc-88e5-11e7-948d-03d79ae7ee7c.png)

**Comment by JosefPihrt** [comment]
@YQuaresma I've fixed the snippet search at http://pihrt.net/Snippetica/Snippets.

**Comment by JosefPihrt** [comment]
@YQuaresma Did you check Code Snippet Manager as I advised?
