### ISSUE TITLE
Support Visual Studio 2022

### ISSUE THREAD

**Issue by alexmajor** [JosefPihrt/Snippetica#37]
I only have Visual Studio 2022 which is not supported.

![image](https://user-images.githubusercontent.com/5017286/180488755-12e3cce4-748a-4cb1-84ca-251e3126f7b7.png)

**Comment by JosefPihrt** [comment]
Hi,

I'm working on it. It should be released within 1-2 weeks.

**Comment by niektuytel** [comment]
Any update on this?
